### ISSUE TITLE
Suggestion: Config to turn off Direseeker

### ISSUE THREAD

**Issue by Expakun** [ArcPh1r3/MinerUnearthed#14]
I like that you recreated the Boss but if I want to use it I will use the Direseeker Mod.

I think if you want an Direseeker Lite as you called it you should just release it as a standalone mod or at least give us a way to turn it off in the Config or with Risk of Options support.

**Comment by TheTimeSweeper** [comment]
direseeker lite is automatically disabled if direseeker is installed. even eithout installed he's can be disabled in config.
kids these days with their risk of options
