### ISSUE TITLE
Bug/Issue: Miner Multiplayer Compatibility.

### ISSUE THREAD

**Issue by CoffeeMaiden** [ArcPh1r3/MinerUnearthed#15]
Hiya, my friends and I enjoy playing Risk of Rain 2 Modded with Character Mods and Miner is already tons of fun, however we have found an issue in Multiplayer involving Miner that prevents most of us from playing the character correctly.

When one player hosts a multiplayer game, the host can play Miner with no problems or issues. However, whenever a player who was not host choose the Miner, the skills were mismatched and not of the Miner's original repertoire. For example, I choose to host a lobby and I played with the "Rocket" character, while my friend choose Miner, we came from a run that was successful where I played Miner with no issues with him playing the "Sniper Classic" character. His primary attack turned into a pure stunning move that did no damage, while his Special (R) Skill turned into the Enforcer's shield up, without the shield.

To check, we swapped roles and I became the player while my friend became the Host and we both went Miner. Miner was working perfectly as intended for him, while my skill set was that of Nemesis Enforcer, Utility (shift) throwing a red smoke grenade and the Special (R) going into a Gatling mode that turned my Primary shot into Nemesis Enforcer's machine gun. 

This is the only time a character in our mod pack doesn't seem to work in this manor, usually all the characters work perfect for host and player, but Miner is the only one with this issue and we couldn't find any way to really solve it.

**Comment by TheTimeSweeper** [comment]
Issues like this always come up because of a mod mismatch. Have one of you export their r2modman profile as code, then everyone (including the first guy) reimport that code into a new profile.
