### ISSUE TITLE
some modded items attach to Miner, but huge.

### ISSUE THREAD

**Issue by tastesliketriangle** [ArcPh1r3/MinerUnearthed#2]
A couple items, notably 2 lunars from [AetheriumMod](https://github.com/KomradeSpectre/AetheriumMod)(Heart of the Void. Unstable Design) will attach to Miner above his head, massively scaled up.

I wasn't sure *who* to report this to, but I tested it with a couple other modded survivors(Executioner and Enforcer) and the issue wasn't visible.

**Comment by TheTimeSweeper** [comment]
fixed
