### ISSUE TITLE
Direseeker Survivor errors/lacking skills

### ISSUE THREAD

**Issue by harry3124** [ArcPh1r3/MinerUnearthed#5]
Upon enabling Direseeker as a survivor, multiple bugs can be seen.

![image](https://user-images.githubusercontent.com/6038359/160442820-478af771-d823-437f-91d3-a95c1553a5ea.png)
Image above - Default Miner's introduction instead of Direseeker's own.

![image](https://user-images.githubusercontent.com/6038359/160442857-5e0de9da-8f3a-4942-b7ac-b9437f387812.png)
![image](https://user-images.githubusercontent.com/6038359/160442881-401ceb11-af4d-4638-90d6-028ce37d7647.png)
Two images, upon the load out menu.

![image](https://user-images.githubusercontent.com/6038359/160443249-3c6ca72a-920c-4a27-a288-6c7ed8878877.png)
Upon spawn. Basic stat of Direseeker is functional, but having no skills to fight.

**Comment by TheTimeSweeper** [comment]
skills fixed with r2api fix, have a good evening
