### ISSUE TITLE
Tristanmcpherson-R2API new update seems to have broken this mod

### ISSUE THREAD

**Issue by AzureFlames** [ArcPh1r3/MinerUnearthed#6]
after the Tristanmcpherson-R2API updated this mod seems to still work but when you go into the character selection screen he does not show up and I don't know if this can help but I think this is the mod console output when launching the game I think well not quite sure but it may have something to do with why this mod is not working anymore but  hope it can help fix with fixing this mod or it could just be something on my end somehow but I have uninstalled ever mod and then redownload just this one and the other required mods to see if it was another mod that was messing with this mod and from the looks of it does not seem like it is because of another mod that I was using.
[Info   : Unity Log] Active scene changed from  to loadingbasic
[Info   : Unity Log] Loaded scene loadingbasic loadSceneMode=2
[Info   :     R2API] [NetworkCompatibility] Adding to the networkModList :
[Info   :     R2API] com.rob.DiggerUnearthed;1.6.8
[Info   :DiggerUnearthed] [Initializing Miner]
[Info   :     R2API] Created a SerializableContentPack for mod com.rob.DiggerUnearthed
[Error  : Unity Log] MissingMethodException: void R2API.DirectorAPI.add_MonsterActions(System.Action`2<System.Collections.Generic.List`1<R2API.DirectorAPI/DirectorCardHolder>, R2API.DirectorAPI/StageInfo>)
Stack trace:
DiggerPlugin.DiggerPlugin.Start () (at <6bacd1204ba0419f89900311c4a53e71>:0)

**Comment by TheTimeSweeper** [comment]
fix uploaded. have a good evening
