### ISSUE TITLE
Simple Chinese language for the mod.

### ISSUE THREAD

**Issue by Edge-R** [ArcPh1r3/MinerUnearthed#9]
I love the mod,so i submit Simple Chinese language for the
[Digger.txt](https://github.com/ArcPh1r3/MinerUnearthed/files/9130087/Digger.txt)
.

**Comment by Edge-R** [comment]
Fixed missing ending text
[Digger.txt](https://github.com/ArcPh1r3/MinerUnearthed/files/9205287/Digger.txt)
.

**Comment by Moffein** [comment]
Apologies for the delay, added this!
When you get the chance, could you translate Misc.txt and DiggerUnlocks.txt as well?
https://github.com/ArcPh1r3/MinerUnearthed/blob/master/language/en/DiggerUnlocks.txt
https://github.com/ArcPh1r3/MinerUnearthed/blob/master/language/en/Misc.txt
